# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
;

require "bundler/gem_tasks"
require "rake/testtask"
require "rdoc/task"
require "yard"
require "yard/rake/yardoc_task"

CLEAN << ["pkg", "doc"]

::Rake::TestTask.new do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = ::FileList["test/test_*.rb"]
end

::RDoc::Task.new do |rd|
  rd.rdoc_dir = "doc"
  rd.main = "README.md"
  rd.rdoc_files.include "README.md", "lib/**/*.rb"
  rd.options << "--line-numbers"
  rd.options << "--all"
end

::YARD::Rake::YardocTask.new

task :default => [:test]
